### ISSUE TITLE
Support for Dark Theme variant

### ISSUE THREAD

**Issue by nexfwall** [gnome-integration-team/firefox-gnome#316] opened 2015-03-30 18:50 UTC
Then using dark adwaita variant and this extensions, Firefox become a bit ugly.

![2015-03-30 21-48-38](https://cloud.githubusercontent.com/assets/8678891/6903990/9a23d754-d726-11e4-865f-bf0cf446a2b0.png)

Dark icons on dark background...

**Comment by nexfwall** [comment] 2015-03-30 19:07
It is a duplicate of #287, but from that point one thing was changed:
Fedora 22 now use GTK3 version of Firefox.

I think this option should be just another checkbox in Extension settings, which will enable dark variant icons and colors for those, who wants it.

And native Firefox does not have any problems with dark themes. When Firefox detects dark theme, it is automatically uses white icons:
![2015-03-30 22-06-59](https://cloud.githubusercontent.com/assets/8678891/6904394/302ae6c8-d729-11e4-978b-5197c69778c5.png)

**Comment by chpii** [comment] 2015-03-31 17:13
@nexfwall If it helps, you can enable it manually: https://github.com/gnome-integration-team/firefox-gnome/issues/37#issuecomment-48126322

**Comment by nexfwall** [comment] 2015-03-31 20:50
It helps, but i prefer to wait a mounth, until full support comes.

**Comment by seleznev** [comment] 2015-04-11 14:49
It's duplicate of #230 and #37 => closed.

@chpii, thanks)

**Closed by seleznev** 2015-04-11 14:49 UTC
