### ISSUE TITLE
Issues on GNOME 3.16 w/ Firefox 37

### ISSUE THREAD

**Issue by yutzhead** [gnome-integration-team/firefox-gnome#325] opened 2015-04-21 14:04 UTC
* The background of the menu bar is missing when using Toolbar Autohide extension 
* Dark mode doesn't work
  * tab bar still light gray
  * websites unreadable because of dark background
  * hovered buttons still light gray

Screenshots:
![screenshot from 2015-04-21 15-55-21](https://cloud.githubusercontent.com/assets/11693340/7253911/0a550e6a-e840-11e4-99f1-0486f6c44355.png)
![screenshot from 2015-04-21 15-55-43](https://cloud.githubusercontent.com/assets/11693340/7253912/0a58a5a2-e840-11e4-866d-d2e236734113.png)
![screenshot from 2015-04-21 15-57-18](https://cloud.githubusercontent.com/assets/11693340/7253913/0a596186-e840-11e4-8733-52be74d4d871.png)

**Comment by seleznev** [comment] 2015-04-21 14:09
What is yours linux distro?

**Comment by yutzhead** [comment] 2015-04-21 16:12
Buckwheat Linux

**Comment by seleznev** [comment] 2015-04-21 16:30
> Buckwheat Linux

I can't found it in Yandex, so this distro doesn't exists for me, sorry.

---

* Theme hasn't dark themes support and you shouldn't use our theme with it.

* Screenshots 2 and 3 looks like you have "bad build" of Firefox. Please try to reproduce this bugs with latest binaries by Mozilla (http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/).

---

I close this issue because it duplicate of #230, #37. If you have any additional information, please provide them, because it can be helpful.

Thank you!

**Closed by seleznev** 2015-04-21 16:30 UTC

**Comment by yutzhead** [comment] 2015-04-21 18:55
It's Firefox on GTK+-3, if that's what you're looking for.
