### ISSUE TITLE
Feature request: please add a greyscale icon for EFF's Privacy Badger to the theme

### ISSUE THREAD

**Issue by pvsomebody** [gnome-integration-team/firefox-gnome#366] opened 2015-09-21 08:34 UTC
It It's along the lines with the extensions you've made greyscale icons for before.

**Comment by 0rAX0** [comment] 2015-09-24 17:45
Thanks for your report but it's a duplicate of #69 , please subscribe yourself there instead.

**Closed by 0rAX0** 2015-09-24 17:45 UTC
